baseURL = "https://acuatre.com/"
defaultContentLanguage = "en"
title = "Alejandro W. Cuatrecasas Schmitz"
theme = "paper"
enableEmoji = false
publishDir = "docs"

[params]
  author = "Alejandro W. Cuatrecasas Schmitz"
  description = "This is my space to write about what I think, what I learn, what I question, and what matters to me."
  monoDarkIcon = true
  readMore = false
  toc = false
  favicon = "favicon.svg"

[taxonomies]
  tag = "tags"

[[menus.main]]
  name = "About"
  url = "/about/"
  weight = 1

[[menus.main]]
  name = "Thoughts"
  url = "/thoughts/"
  weight = 2

[[menus.main]]
  name = "Good stuff"
  url = "/good-stuff/"
  weight = 3

[[menus.main]]
  name = "Questions"
  url = "/questions/"
  weight = 4
